spring:
  application:
    name: cms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/manuelrojas19/cms-config-repo
          clone-on-start: true
          default-label: main
          search-paths: '{application}'
server:
  port: 8888
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
