server:
  port: 8888
spring:
  application:
    name: cms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/manuelrojas19/cms-config-repo
          clone-on-start: true
          search-paths: '{application}'
          default-label: main